### ISSUE TITLE
missing args.meta

### ISSUE THREAD

**Issue by Jiajia0319** [maestrojeong/Deep-Hash-Table-CVPR19#1]
Hi, thanks for your code, but I have a problem when I run the train_model in cifer_exps/ours/main.py, there is no “cifar_metric_triplet_256/meta/meta.pkl”, may I know where does it come from? 
And at first we do not have checkpoints, so "model.restore(args.save)"  should not be used, right?

Thank you.

**Comment by maestrojeong** [comment]
Q:may I know where does it come from?
A: You have to run function "integrate_.." in 'cifar_exps/metric/main.py ' after training the metric learning model.

Q:at first we do not have checkpoints, so "model.restore(args.save)" should not be used, right?
A:Yes you are right.

Thank you
If you have any more questions, feel free to ask me.

**Comment by Jiajia0319** [comment]
@maestrojeong Thanks for your reply ~
